<a href="https://colab.research.google.com/github/nbs19/deep-learning/blob/main/step1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!ls

mobile_cleaned.csv  sample_data

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('mobile_cleaned.csv')
df.head()

   sim_type  aperture  gpu_rank  ...  battery_capacity  processor_rank  is_liked
0         0        12        55  ...              2000             125         1
1         0         1        55  ...              2000             165         1
2         0         9        55  ...              2500             164         0
3         0         8        55  ...              3000             165         1
4         1         1        55  ...              3000             165         0

[5 rows x 40 columns]

In [7]:
df.tail()

     sim_type  aperture  gpu_rank  ...  battery_capacity  processor_rank  is_liked
104         3        10        14  ...              3410               8         1
105         0         5         3  ...              3600             101         1
106         3        10         6  ...              2750               1         1
107         3        10        12  ...              1810               7         1
108         2         8         3  ...              3000               2         0

[5 rows x 40 columns]

In [8]:
dir(df)

['FM',
 'T',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_builtin_table',
 '_can_fast_transpose',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iter_column_arrays',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'aperture',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'auto_focus',
 'axes',
 'backfill',
 'battery_capacity',
 'battery_type',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'brand_rank',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'display_resolution',
 'display_type',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expandable_memory',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flash_type',
 'floordiv',
 'frames_per_second',
 'from_dict',
 'from_records',
 'front_camera_resolution',
 'ge',
 'get',
 'gpu_rank',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'internal_memory',
 'interpolate',
 'is_liked',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'micro_sd_slot',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'no_of_cores',
 'no_of_reviews_in_gsmarena_in_week',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'os',
 'pad',
 'pct_change',
 'phone_height',
 'phone_width',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'price',
 'primary_camera_resolution',
 'processor_frequency',
 'processor_rank',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'ram_memory',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'removable_battery',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'screen_pixel_density',
 'screen_protection',
 'screen_size',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'sim_size',
 'sim_type',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'stand_by_time',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'talk_time',
 'thickness',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'usb_type',
 'value_counts',
 'values',
 'var',
 'version',
 'video_resolution',
 'water_proof_rate',
 'weight',
 'where',
 'xs']

In [9]:
len(df)

109

In [10]:
df.shape

(109, 40)

In [11]:
df.loc[10]

sim_type                                0.0
aperture                                1.0
gpu_rank                               55.0
weight                                169.0
stand_by_time                         514.0
processor_frequency                     1.3
thickness                               7.9
flash_type                              2.0
front_camera_resolution                 2.0
auto_focus                              3.0
screen_size                             5.0
frames_per_second                      30.0
FM                                      3.0
no_of_reviews_in_gsmarena_in_week       5.0
os                                      0.0
phone_height                          152.0
screen_protection                      26.0
sim_size                                3.0
price                                6749.0
talk_time                              14.0
video_resolution                      720.0
display_resolution                      4.0
removable_battery                       1.0
display_type                            2.0
primary_camera_resolution               8.0
battery_type                            2.0
ram_memory                              2.0
internal_memory                         7.0
brand_rank                              4.0
no_of_cores                             6.0
micro_sd_slot                           4.0
screen_pixel_density                    9.0
water_proof_rate                        3.0
phone_width                            75.0
expandable_memory                      32.0
version                                 5.0
usb_type                                4.0
battery_capacity                     4000.0
processor_rank                        126.0
is_liked                                1.0
Name: 10, dtype: float64

In [13]:
df_short=df[0:15]
df.shape
df.head()

   sim_type  aperture  gpu_rank  ...  battery_capacity  processor_rank  is_liked
0         0        12        55  ...              2000             125         1
1         0         1        55  ...              2000             165         1
2         0         9        55  ...              2500             164         0
3         0         8        55  ...              3000             165         1
4         1         1        55  ...              3000             165         0

[5 rows x 40 columns]

In [20]:
df_thin=df[['stand_by_time','expandable_memory','price','battery_capacity','is_liked']]
df_thin.head()

   stand_by_time  expandable_memory  price  battery_capacity  is_liked
0            250               64.0   3870              2000         1
1            300               32.0   4059              2000         1
2            329               32.0   4777              2500         0
3            385               32.0   5799              3000         1
4            385               32.0   5990              3000         0

In [22]:
df_liked=df[df['is_liked']==1]
print(df_liked)

     sim_type  aperture  gpu_rank  ...  battery_capacity  processor_rank  is_liked
0           0        12        55  ...              2000             125         1
1           0         1        55  ...              2000             165         1
3           0         8        55  ...              3000             165         1
6           1         1        56  ...              1700             163         1
7           0         8        41  ...              2000              92         1
..        ...       ...       ...  ...               ...             ...       ...
103         3         8         9  ...              3430               5         1
104         3        10        14  ...              3410               8         1
105         0         5         3  ...              3600             101         1
106         3        10         6  ...              2750               1         1
107         3        10        12  ...              1810               7         1

[92 rows x 40 columns]

In [26]:
df['price'].describe()

count      109.000000
mean     19373.211009
std      14039.197220
min       3870.000000
25%       8999.000000
50%      14614.000000
75%      24999.000000
max      64500.000000
Name: price, dtype: float64

In [27]:
df['price'].mean()

19373.211009174312

In [33]:

df_thin[df_thin['is_liked']==1]['price'].mean()

19393.239130434784

In [37]:
g=df_thin.groupby(['is_liked'])
for key, kay in g:
  print(key)
  print(kay)

0
     stand_by_time  expandable_memory  price  battery_capacity  is_liked
2              329               32.0   4777              2500         0
4              385               32.0   5990              3000         0
5              280               32.0   5999              2900         0
11             300              128.0   6990              2600         0
22             354              128.0   7999              2400         0
38             490               32.0   9999              2100         0
53             345               64.0  14300              2950         0
60             840                0.0  15689              4100         0
74             390              128.0  21999              2800         0
77             620              128.0  22999              3100         0
78             618                0.0  24499              3600         0
80             598                0.0  24999              3000         0
83             504              200.0  25500              2600         0
90             500                0.0  34999              3760         0
91             240                0.0  34999              1624         0
95             580              256.0  37766              2840         0
108            400                0.0  27999              3000         0
1
     stand_by_time  expandable_memory  price  battery_capacity  is_liked
0              250               64.0   3870              2000         1
1              300               32.0   4059              2000         1
3              385               32.0   5799              3000         1
6              230              128.0   5999              1700         1
7              182               32.0   6599              2000         1
..             ...                ...    ...               ...       ...
103            600              256.0  52699              3430         1
104            540              256.0  54900              3410         1
105            400              200.0  56900              3600         1
106            384                0.0  59000              2750         1
107            250                0.0  64500              1810         1

[92 rows x 5 columns]